site_name: ${{values.spa_name | dump}}
site_description: ${{values.description | dump}}

nav:
  - Introduction: index.md
  - FAQs: faqs.md
  - Contribution: contribution.md
  - Code Of Conduct: coc.md

plugins:
  - techdocs-core
